### ISSUE TITLE
Submit the latest update to PyPI

### ISSUE THREAD

**Issue by Ryanb58** [smartfile/client-python#10]
When we get a chance, we need to add the changes made in https://github.com/smartfile/client-python/pull/7 to PyPI. This way people can just use `pip install smartfile` to import the latest SmartFile client SDK changes.

**Comment by lsapan** [comment]
Any chance this can be done? It would resolve #6 and would be super appreciated! 👍

**Comment by cabarnes** [comment]
PyPI has been updated.
