### ISSUE TITLE
<class Client> has no function 'upload()'

### ISSUE THREAD

**Issue by Odame** [smartfile/client-python#12]
When the library is installed via pip, it doesn't contain the definition of the upload() function in the Client class.
This results in an error when upload() is called on a BasicClient object.
It appears the source code I got in my venv/Lib/site-packages/smartfile/__init__.py is different from what is published on github.

**Comment by cabarnes** [comment]
@Odame This should be fixed now that the PyPI version has been updated.

**Comment by Ryanb58** [comment]
Much rejoice for getting this pushed to PyPi! Thanks @cabarnes
