### ISSUE TITLE
Moving files

### ISSUE THREAD

**Issue by LinusSkucas** [smartfile/client-python#24]
Hello,
According to the examples I should be able to go
api.move('file.txt', '/screenShot')
to move file.txt to screenShot.

However, I am getting the error:
Response 409: Error: b'{"detail": "Destination exists:/screenShot"}'
The api.move method used to work for me. Now it has stopped. Does anyone know how to fix this?

Thanks

**Comment by Ryanb58** [comment]
Hey LinusS1. Sorry my response took so long. I have had quite a few github notifications lately. 

It looks like the documentation is incorrect. Thank you for pointing this out. I tested the code you provided and ended up having to specify the destination file name as well. 

Below is the code that was successful for me. Does this work for you? If so I'll update the documentation.

```
api.move('file.txt', '/screenShot/file.txt')
```

Also, I am curious to how long your script has been in use. This will help me determine if it was an issue with a code change for our API server.
