### ISSUE TITLE
README should be changed.

### ISSUE THREAD

**Issue by Ryanb58** [smartfile/client-python#8]
Currently, the readme is of the form "restructured text". To keep things consistent across repositories we should update this to be a part of the markdown family instead.

**Comment by btimby** [comment]
NO, it should not change to md. rST is used because Python Package Index uses rST, and github also supports rST.

**Comment by travcunn** [comment]
Here is an example setup.py which allows your Python package to use Markdown (check out line 8)
https://github.com/smartfile/file-versioning/blob/master/setup.py

**Comment by giampaolo** [comment]
> Here is an example setup.py which allows your Python package to use Markdow
It requires pypandoc lib though.

**Comment by travcunn** [comment]
yeah true :(
